name: Deploy Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run validate
      - run: npm run build
      - run: npm install -g surge
      - run:
          surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{
          secrets.SURGE_TOKEN }}
